/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Login controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Token } from "../models";

@Injectable({ providedIn: "root" })
export class LoginService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    loginAccessTokenApiV1LoginAccessTokenPost(username: string, password: string, grant_type?: any, scope?: string, client_id?: any, client_secret?: any, rememberMe?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<Token>;
    loginAccessTokenApiV1LoginAccessTokenPost(username: string, password: string, grant_type?: any, scope?: string, client_id?: any, client_secret?: any, rememberMe?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Token>>;
    loginAccessTokenApiV1LoginAccessTokenPost(username: string, password: string, grant_type?: any, scope?: string, client_id?: any, client_secret?: any, rememberMe?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Token>>;
    loginAccessTokenApiV1LoginAccessTokenPost(username: string, password: string, grant_type?: any, scope?: string, client_id?: any, client_secret?: any, rememberMe?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/login/access-token`;

        let params = new HttpParams();
        if (rememberMe != null) {
            params = HttpParamsBuilder.addToHttpParams(params, rememberMe, 'remember_me');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for URL-encoded form data
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/x-www-form-urlencoded');
        }

        const formBody = new URLSearchParams();
        if (grant_type !== undefined && grant_type !== null) {
            formBody.append('grant_type', String(grant_type));
        }
        if (username !== undefined && username !== null) {
            formBody.append('username', String(username));
        }
        if (password !== undefined && password !== null) {
            formBody.append('password', String(password));
        }
        if (scope !== undefined && scope !== null) {
            formBody.append('scope', String(scope));
        }
        if (client_id !== undefined && client_id !== null) {
            formBody.append('client_id', String(client_id));
        }
        if (client_secret !== undefined && client_secret !== null) {
            formBody.append('client_secret', String(client_secret));
        }

        return this.httpClient.request('post', url, {
            body: formBody.toString(),
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
