/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Propiedades controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PropiedadesPublic, PropiedadForm, PropiedadPublic, PropiedadUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class PropiedadesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    readPropiedadesApiV1PropiedadesGet(skip?: number, limit?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadesPublic>;
    readPropiedadesApiV1PropiedadesGet(skip?: number, limit?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadesPublic>>;
    readPropiedadesApiV1PropiedadesGet(skip?: number, limit?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadesPublic>>;
    readPropiedadesApiV1PropiedadesGet(skip?: number, limit?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/`;

        let params = new HttpParams();
        if (skip != null) {
            params = HttpParamsBuilder.addToHttpParams(params, skip, 'skip');
        }
        if (limit != null) {
            params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createPropiedadEndpointApiV1PropiedadesPost(form: PropiedadForm, foto_principal: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    createPropiedadEndpointApiV1PropiedadesPost(form: PropiedadForm, foto_principal: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    createPropiedadEndpointApiV1PropiedadesPost(form: PropiedadForm, foto_principal: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    createPropiedadEndpointApiV1PropiedadesPost(form: PropiedadForm, foto_principal: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (form !== undefined) {
            formData.append('form', String(form));
        }
        if (foto_principal !== undefined) {
            formData.append('foto_principal', String(foto_principal));
        }

        return this.httpClient.request('post', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    readPropiedadByIdApiV1PropiedadesPropiedadIdGet(propiedadId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    readPropiedadByIdApiV1PropiedadesPropiedadIdGet(propiedadId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    readPropiedadByIdApiV1PropiedadesPropiedadIdGet(propiedadId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    readPropiedadByIdApiV1PropiedadesPropiedadIdGet(propiedadId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updatePropiedadEndpointApiV1PropiedadesPropiedadIdPatch(propiedadId: string, propiedadUpdate: PropiedadUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    updatePropiedadEndpointApiV1PropiedadesPropiedadIdPatch(propiedadId: string, propiedadUpdate: PropiedadUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    updatePropiedadEndpointApiV1PropiedadesPropiedadIdPatch(propiedadId: string, propiedadUpdate: PropiedadUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    updatePropiedadEndpointApiV1PropiedadesPropiedadIdPatch(propiedadId: string, propiedadUpdate: PropiedadUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: propiedadUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deletePropiedadEndpointApiV1PropiedadesPropiedadIdDelete(propiedadId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Record<string, any>>;
    deletePropiedadEndpointApiV1PropiedadesPropiedadIdDelete(propiedadId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Record<string, any>>>;
    deletePropiedadEndpointApiV1PropiedadesPropiedadIdDelete(propiedadId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Record<string, any>>>;
    deletePropiedadEndpointApiV1PropiedadesPropiedadIdDelete(propiedadId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    replaceFotoPrincipalEndpointApiV1PropiedadesPropiedadIdFotoPrincipalPost(propiedadId: string, file: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    replaceFotoPrincipalEndpointApiV1PropiedadesPropiedadIdFotoPrincipalPost(propiedadId: string, file: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    replaceFotoPrincipalEndpointApiV1PropiedadesPropiedadIdFotoPrincipalPost(propiedadId: string, file: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    replaceFotoPrincipalEndpointApiV1PropiedadesPropiedadIdFotoPrincipalPost(propiedadId: string, file: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}/foto-principal`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', String(file));
        }

        return this.httpClient.request('post', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addFotoEndpointApiV1PropiedadesPropiedadIdFotosPost(propiedadId: string, file: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    addFotoEndpointApiV1PropiedadesPropiedadIdFotosPost(propiedadId: string, file: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    addFotoEndpointApiV1PropiedadesPropiedadIdFotosPost(propiedadId: string, file: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    addFotoEndpointApiV1PropiedadesPropiedadIdFotosPost(propiedadId: string, file: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}/fotos`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', String(file));
        }

        return this.httpClient.request('post', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteFotoEndpointApiV1PropiedadesPropiedadIdFotosFotoIdDelete(propiedadId: string, fotoId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PropiedadPublic>;
    deleteFotoEndpointApiV1PropiedadesPropiedadIdFotosFotoIdDelete(propiedadId: string, fotoId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PropiedadPublic>>;
    deleteFotoEndpointApiV1PropiedadesPropiedadIdFotosFotoIdDelete(propiedadId: string, fotoId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PropiedadPublic>>;
    deleteFotoEndpointApiV1PropiedadesPropiedadIdFotosFotoIdDelete(propiedadId: string, fotoId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/propiedades/${propiedadId}/fotos/${fotoId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
