/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Users controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, UserPublic, UserUpdate, UsersPublic, UserCreate } from "../models";

@Injectable({ providedIn: "root" })
export class UsersService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    readUserMeApiV1UsersMeGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserPublic>;
    readUserMeApiV1UsersMeGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserPublic>>;
    readUserMeApiV1UsersMeGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserPublic>>;
    readUserMeApiV1UsersMeGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/me`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateUserMeApiV1UsersMePatch(userUpdate: UserUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserPublic>;
    updateUserMeApiV1UsersMePatch(userUpdate: UserUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserPublic>>;
    updateUserMeApiV1UsersMePatch(userUpdate: UserUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserPublic>>;
    updateUserMeApiV1UsersMePatch(userUpdate: UserUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/me`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    readUsersApiV1UsersGet(skip?: number, limit?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<UsersPublic>;
    readUsersApiV1UsersGet(skip?: number, limit?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UsersPublic>>;
    readUsersApiV1UsersGet(skip?: number, limit?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UsersPublic>>;
    readUsersApiV1UsersGet(skip?: number, limit?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/`;

        let params = new HttpParams();
        if (skip != null) {
            params = HttpParamsBuilder.addToHttpParams(params, skip, 'skip');
        }
        if (limit != null) {
            params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createUserEndpointApiV1UsersPost(userCreate: UserCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserPublic>;
    createUserEndpointApiV1UsersPost(userCreate: UserCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserPublic>>;
    createUserEndpointApiV1UsersPost(userCreate: UserCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserPublic>>;
    createUserEndpointApiV1UsersPost(userCreate: UserCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userCreate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    readUserByIdApiV1UsersUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserPublic>;
    readUserByIdApiV1UsersUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserPublic>>;
    readUserByIdApiV1UsersUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserPublic>>;
    readUserByIdApiV1UsersUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateUserEndpointApiV1UsersUserIdPatch(userId: string, userUpdate: UserUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserPublic>;
    updateUserEndpointApiV1UsersUserIdPatch(userId: string, userUpdate: UserUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserPublic>>;
    updateUserEndpointApiV1UsersUserIdPatch(userId: string, userUpdate: UserUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserPublic>>;
    updateUserEndpointApiV1UsersUserIdPatch(userId: string, userUpdate: UserUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteUserApiV1UsersUserIdDelete(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Record<string, any>>;
    deleteUserApiV1UsersUserIdDelete(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Record<string, any>>>;
    deleteUserApiV1UsersUserIdDelete(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Record<string, any>>>;
    deleteUserApiV1UsersUserIdDelete(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
