/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface BodyAddFotoEndpointApiV1Propiedades_PropiedadId_FotosPost {
    file: string;
}

export interface BodyCreatePropiedadEndpointApiV1Propiedades_Post {
    nombre: string;
    descripcion: string;
    ubicacion: string;
    precio: number | string;
    tipo: 'venta' | 'arriendo';
    foto_principal: string;
}

export interface BodyLoginAccessTokenApiV1LoginAccessTokenPost {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
}

export interface BodyReplaceFotoPrincipalEndpointApiV1Propiedades_PropiedadId_FotoPrincipalPost {
    file: string;
}

export interface HTTPValidationError {
    detail?: Array<ValidationError>;
}

export interface PropiedadFotoPublic {
    id: string;
    orden: number;
    url: string;
}

export interface PropiedadPublic {
    id: string;
    nombre: string;
    descripcion: string;
    ubicacion: string;
    precio: string;
    tipo: string;
    orden: number;
    foto_principal_url: string;
    fotos: Array<PropiedadFotoPublic>;
}

export interface PropiedadUpdate {
    nombre?: string | null;
    descripcion?: string | null;
    ubicacion?: string | null;
    precio?: number | string | null;
    tipo?: 'venta' | 'arriendo' | null;
}

export interface PropiedadesPublic {
    data: Array<PropiedadPublic>;
    count: number;
}

export interface PropiedadesReorder {
    ids: Array<string>;
}

export interface Token {
    access_token: string;
    token_type?: string;
}

export interface UserCreate {
    email: string;
    password: string;
    full_name?: string | null;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: string;
}

export interface UserPublic {
    id: string;
    email: string;
    full_name: string | null;
    is_active: boolean;
    is_superuser: boolean;
    role: string;
}

export interface UserUpdate {
    email?: string | null;
    password?: string | null;
    full_name?: string | null;
    is_active?: boolean | null;
    role?: string | null;
}

export interface UsersPublic {
    data: Array<UserPublic>;
    count: number;
}

export interface ValidationError {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: any;
    ctx?: Record<string, unknown>;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
