/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface BodyLoginAccessTokenApiV1LoginAccessTokenPost {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
}

export interface HTTPValidationError {
    detail?: Array<ValidationError>;
}

export interface Token {
    access_token: string;
    token_type?: string;
}

export interface UserCreate {
    email: string;
    password: string;
    full_name?: string | null;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: string;
}

export interface UserPublic {
    id: string;
    email: string;
    full_name: string | null;
    is_active: boolean;
    is_superuser: boolean;
    role: string;
}

export interface UserUpdate {
    email?: string | null;
    password?: string | null;
    full_name?: string | null;
    is_active?: boolean | null;
    role?: string | null;
}

export interface UsersPublic {
    data: Array<UserPublic>;
    count: number;
}

export interface ValidationError {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: any;
    ctx?: Record<string, unknown>;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
