"""propiedades_whatsapp

Revision ID: 015500d86b2b
Revises: b761541276fd
Create Date: 2026-08-06 22:47:29.770248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '015500d86b2b'
down_revision: Union[str, None] = 'b761541276fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'whatsapp')
    # ### end Alembic commands ###
