"""reportes_dano

Revision ID: 04651fd80980
Revises: 951b3bf27674
Create Date: 2026-08-04 15:40:07.964083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '04651fd80980'
down_revision: Union[str, None] = '951b3bf27674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_dano',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('medio_comunicacion', sa.String(length=20), nullable=True),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('tipo_reporte', sa.String(length=30), nullable=False),
    sa.Column('tipo_reporte_otro', sa.String(length=100), nullable=True),
    sa.Column('descripcion_dano', sa.Text(), nullable=False),
    sa.Column('fotos', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_dano')
    # ### end Alembic commands ###
