"""solicitudes_venta_numero_sugerencias

Revision ID: 0fa018845407
Revises: 6e5b91998815
Create Date: 2026-07-31 19:29:47.375562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fa018845407'
down_revision: Union[str, None] = '6e5b91998815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_venta', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('solicitudes_venta', sa.Column('sugerencias', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_venta', 'sugerencias')
    op.drop_column('solicitudes_venta', 'numero')
    # ### end Alembic commands ###
