"""agregar zona_lavanderia a propiedades

Revision ID: 30ebe3d66e75
Revises: 5724da3da0fa
Create Date: 2026-08-23 17:25:40.842698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30ebe3d66e75'
down_revision: Union[str, None] = '5724da3da0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('zona_lavanderia', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'zona_lavanderia')
    # ### end Alembic commands ###
