"""propiedades detalle inmueble

Revision ID: 3e0494416ae6
Revises: 4e63c15c0052
Create Date: 2026-07-26 12:42:02.353805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e0494416ae6'
down_revision: Union[str, None] = '4e63c15c0052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('tipo_inmueble', sa.String(length=20), server_default='casa', nullable=False))
    op.add_column('propiedades', sa.Column('banos', sa.Integer(), nullable=True))
    op.add_column('propiedades', sa.Column('habitaciones', sa.Integer(), nullable=True))
    op.add_column('propiedades', sa.Column('tiene_parqueadero', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('num_parqueaderos', sa.Integer(), nullable=True))
    op.add_column('propiedades', sa.Column('area_construida', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('propiedades', sa.Column('antiguedad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'antiguedad')
    op.drop_column('propiedades', 'area_construida')
    op.drop_column('propiedades', 'num_parqueaderos')
    op.drop_column('propiedades', 'tiene_parqueadero')
    op.drop_column('propiedades', 'habitaciones')
    op.drop_column('propiedades', 'banos')
    op.drop_column('propiedades', 'tipo_inmueble')
    # ### end Alembic commands ###
