"""citas

Revision ID: 48c4ef3e0d57
Revises: 92937a77182b
Create Date: 2026-08-01 17:33:53.493644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48c4ef3e0d57'
down_revision: Union[str, None] = '92937a77182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('nombre_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('solicitud_venta_id', sa.Uuid(), nullable=True),
    sa.Column('solicitud_arriendo_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT (solicitud_venta_id IS NOT NULL AND solicitud_arriendo_id IS NOT NULL)', name='ck_citas_un_solo_vinculo'),
    sa.ForeignKeyConstraint(['solicitud_arriendo_id'], ['solicitudes_arriendo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_venta_id'], ['solicitudes_venta.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_fecha_fin'), 'citas', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_citas_fecha_inicio'), 'citas', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_citas_solicitud_arriendo_id'), 'citas', ['solicitud_arriendo_id'], unique=False)
    op.create_index(op.f('ix_citas_solicitud_venta_id'), 'citas', ['solicitud_venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citas_solicitud_venta_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_solicitud_arriendo_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_fecha_inicio'), table_name='citas')
    op.drop_index(op.f('ix_citas_fecha_fin'), table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
