"""propiedades_orden

Revision ID: 4e63c15c0052
Revises: a2e4f4fa354c
Create Date: 2026-07-23 20:07:11.582846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e63c15c0052'
down_revision: Union[str, None] = 'a2e4f4fa354c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('orden', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'orden')
    # ### end Alembic commands ###
