"""proyectos

Revision ID: 52dce5847fbd
Revises: 3e0494416ae6
Create Date: 2026-07-29 02:56:40.161163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52dce5847fbd'
down_revision: Union[str, None] = '3e0494416ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('foto_portada_key', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyectos')
    # ### end Alembic commands ###
