"""propiedades_gravamenes_hipoteca

Revision ID: 540340db17ca
Revises: 015500d86b2b
Create Date: 2026-08-06 23:34:13.930595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '540340db17ca'
down_revision: Union[str, None] = '015500d86b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('tiene_gravamenes', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('tiene_hipoteca', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'tiene_hipoteca')
    op.drop_column('propiedades', 'tiene_gravamenes')
    # ### end Alembic commands ###
