"""propiedades_detalle_por_tipo_inmueble

Revision ID: 685c64e1b1a2
Revises: 52dce5847fbd
Create Date: 2026-07-29 23:00:01.629315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '685c64e1b1a2'
down_revision: Union[str, None] = '52dce5847fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('tipo_parqueadero', sa.String(length=20), nullable=True))
    op.add_column('propiedades', sa.Column('area_lote', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('propiedades', sa.Column('frente', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('propiedades', sa.Column('fondo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('propiedades', sa.Column('piso', sa.Integer(), nullable=True))
    op.add_column('propiedades', sa.Column('vista', sa.String(length=20), nullable=True))
    op.add_column('propiedades', sa.Column('balcon', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('terraza', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('patio', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('bodega', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('zona_bbq', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('piscina', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('cocina', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('conjunto_cerrado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('tiene_administracion', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('valor_administracion', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('propiedades', sa.Column('zonas_comunes', sa.Text(), nullable=True))
    op.add_column('propiedades', sa.Column('actividad', sa.Text(), nullable=True))
    op.add_column('propiedades', sa.Column('rural_urbano', sa.String(length=10), nullable=True))
    op.add_column('propiedades', sa.Column('tiene_servicios', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('tiene_alcantarillado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('tiene_acueducto', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('permite_permuta', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('adicionales', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'adicionales')
    op.drop_column('propiedades', 'permite_permuta')
    op.drop_column('propiedades', 'tiene_acueducto')
    op.drop_column('propiedades', 'tiene_alcantarillado')
    op.drop_column('propiedades', 'tiene_servicios')
    op.drop_column('propiedades', 'rural_urbano')
    op.drop_column('propiedades', 'actividad')
    op.drop_column('propiedades', 'zonas_comunes')
    op.drop_column('propiedades', 'valor_administracion')
    op.drop_column('propiedades', 'tiene_administracion')
    op.drop_column('propiedades', 'conjunto_cerrado')
    op.drop_column('propiedades', 'cocina')
    op.drop_column('propiedades', 'piscina')
    op.drop_column('propiedades', 'zona_bbq')
    op.drop_column('propiedades', 'bodega')
    op.drop_column('propiedades', 'patio')
    op.drop_column('propiedades', 'terraza')
    op.drop_column('propiedades', 'balcon')
    op.drop_column('propiedades', 'vista')
    op.drop_column('propiedades', 'piso')
    op.drop_column('propiedades', 'fondo')
    op.drop_column('propiedades', 'frente')
    op.drop_column('propiedades', 'area_lote')
    op.drop_column('propiedades', 'tipo_parqueadero')
    # ### end Alembic commands ###
