"""solicitudes_venta

Revision ID: 6e5b91998815
Revises: 59f3e031691a
Create Date: 2026-07-30 18:00:19.343000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e5b91998815'
down_revision: Union[str, None] = '59f3e031691a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('medio_comunicacion', sa.String(length=20), nullable=False),
    sa.Column('presupuesto_total', sa.String(length=100), nullable=False),
    sa.Column('forma_pago', sa.String(length=30), nullable=False),
    sa.Column('sectores_interes', sa.String(length=255), nullable=True),
    sa.Column('valor_disponible_credito', sa.String(length=100), nullable=True),
    sa.Column('valor_disponible_contado', sa.String(length=100), nullable=True),
    sa.Column('forma_pago_otro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_venta')
    # ### end Alembic commands ###
