"""solicitudes_arriendo

Revision ID: 92937a77182b
Revises: 0fa018845407
Create Date: 2026-07-31 19:56:45.953495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92937a77182b'
down_revision: Union[str, None] = '0fa018845407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_arriendo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('sector_interes', sa.String(length=255), nullable=False),
    sa.Column('precio_maximo', sa.String(length=100), nullable=False),
    sa.Column('medio_contacto', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_arriendo')
    # ### end Alembic commands ###
