"""solicitudes_arrendar_propiedad

Revision ID: 951b3bf27674
Revises: 48c4ef3e0d57
Create Date: 2026-08-03 21:26:37.917370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '951b3bf27674'
down_revision: Union[str, None] = '48c4ef3e0d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_arrendar_propiedad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=255), nullable=False),
    sa.Column('medio_comunicacion', sa.String(length=20), nullable=True),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('direccion_inmueble', sa.String(length=255), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_arrendar_propiedad')
    # ### end Alembic commands ###
