"""solicitudes_publicar_propiedad_y_extender_arrendar

Revision ID: a16b9805fa81
Revises: de495bfc44b1
Create Date: 2026-08-07 19:41:34.904086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a16b9805fa81'
down_revision: Union[str, None] = 'de495bfc44b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_publicar_propiedad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=255), nullable=False),
    sa.Column('medio_comunicacion', sa.String(length=20), nullable=True),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('direccion_inmueble', sa.String(length=255), nullable=False),
    sa.Column('precio_estimado', sa.String(length=100), nullable=True),
    sa.Column('descripcion_caracteristicas', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('solicitudes_arrendar_propiedad', sa.Column('precio_estimado', sa.String(length=100), nullable=True))
    op.add_column('solicitudes_arrendar_propiedad', sa.Column('descripcion_caracteristicas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_arrendar_propiedad', 'descripcion_caracteristicas')
    op.drop_column('solicitudes_arrendar_propiedad', 'precio_estimado')
    op.drop_table('solicitudes_publicar_propiedad')
    # ### end Alembic commands ###
