"""propiedades

Revision ID: a2e4f4fa354c
Revises: 3a9d42b635ec
Create Date: 2026-07-22 19:30:45.665032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2e4f4fa354c'
down_revision: Union[str, None] = '3a9d42b635ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propiedades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('foto_principal_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propiedad_fotos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('propiedad_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propiedad_fotos_propiedad_id'), 'propiedad_fotos', ['propiedad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propiedad_fotos_propiedad_id'), table_name='propiedad_fotos')
    op.drop_table('propiedad_fotos')
    op.drop_table('propiedades')
    # ### end Alembic commands ###
