"""agregar solicitudes_trabajo

Revision ID: b622a694e0b5
Revises: 30ebe3d66e75
Create Date: 2026-08-23 18:26:47.095836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b622a694e0b5'
down_revision: Union[str, None] = '30ebe3d66e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_trabajo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('hoja_de_vida_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_trabajo')
    # ### end Alembic commands ###
