"""proyectos_precio_financiacion_estado

Revision ID: b761541276fd
Revises: 04651fd80980
Create Date: 2026-08-05 10:40:23.964439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b761541276fd'
down_revision: Union[str, None] = '04651fd80980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('precio', sa.Integer(), server_default='0', nullable=False))
    op.add_column('proyectos', sa.Column('financiacion', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('proyectos', sa.Column('financiacion_descripcion', sa.Text(), nullable=True))
    op.add_column('proyectos', sa.Column('credito_hipotecario', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Migración de datos: estado pasa de 3 a 4 valores (preventa/en_construccion/
    # entrega_inmediata -> planos/construccion_1/construccion_2/entrega_inmediata).
    op.execute("UPDATE proyectos SET estado = 'planos' WHERE estado = 'preventa'")
    op.execute("UPDATE proyectos SET estado = 'construccion_1' WHERE estado = 'en_construccion'")


def downgrade() -> None:
    # Downgrade de datos: construccion_2 no tiene equivalente en el esquema anterior,
    # se colapsa a 'en_construccion' igual que construccion_1 (pérdida de granularidad
    # aceptada en el downgrade).
    op.execute("UPDATE proyectos SET estado = 'preventa' WHERE estado = 'planos'")
    op.execute("UPDATE proyectos SET estado = 'en_construccion' WHERE estado = 'construccion_1'")
    op.execute("UPDATE proyectos SET estado = 'en_construccion' WHERE estado = 'construccion_2'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'credito_hipotecario')
    op.drop_column('proyectos', 'financiacion_descripcion')
    op.drop_column('proyectos', 'financiacion')
    op.drop_column('proyectos', 'precio')
    # ### end Alembic commands ###
