"""proyectos_zonas_tipos_admin_fotos

Revision ID: de495bfc44b1
Revises: 540340db17ca
Create Date: 2026-08-07 17:51:02.452479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de495bfc44b1'
down_revision: Union[str, None] = '540340db17ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyecto_fotos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_fotos_proyecto_id'), 'proyecto_fotos', ['proyecto_id'], unique=False)
    op.create_table('proyecto_tipos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('habitaciones', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('balcon', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('terraza', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parqueadero', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('patio', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vista', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_tipos_proyecto_id'), 'proyecto_tipos', ['proyecto_id'], unique=False)
    op.add_column('proyectos', sa.Column('credito_hipotecario_descripcion', sa.Text(), nullable=True))
    op.add_column('proyectos', sa.Column('tiene_zonas_comunes', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('proyectos', sa.Column('zonas_comunes', postgresql.ARRAY(sa.String(length=30)), nullable=True))
    op.add_column('proyectos', sa.Column('ascensor', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('proyectos', sa.Column('conjunto_cerrado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('proyectos', sa.Column('valor_administracion_por_definir', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('proyectos', sa.Column('valor_administracion', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('proyectos', sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'area_m2')
    op.drop_column('proyectos', 'valor_administracion')
    op.drop_column('proyectos', 'valor_administracion_por_definir')
    op.drop_column('proyectos', 'conjunto_cerrado')
    op.drop_column('proyectos', 'ascensor')
    op.drop_column('proyectos', 'zonas_comunes')
    op.drop_column('proyectos', 'tiene_zonas_comunes')
    op.drop_column('proyectos', 'credito_hipotecario_descripcion')
    op.drop_index(op.f('ix_proyecto_tipos_proyecto_id'), table_name='proyecto_tipos')
    op.drop_table('proyecto_tipos')
    op.drop_index(op.f('ix_proyecto_fotos_proyecto_id'), table_name='proyecto_fotos')
    op.drop_table('proyecto_fotos')
    # ### end Alembic commands ###
