"""solicitudes_documentos_propietario_y_propiedad_destacada

Revision ID: e1e2cae50d8d
Revises: a16b9805fa81
Create Date: 2026-08-08 00:43:03.488773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1e2cae50d8d'
down_revision: Union[str, None] = 'a16b9805fa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_documentos_propietario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('plan_contratado', sa.String(length=30), nullable=False),
    sa.Column('cedula_key', sa.String(length=500), nullable=False),
    sa.Column('certificado_libertad_key', sa.String(length=500), nullable=False),
    sa.Column('escritura_key', sa.String(length=500), nullable=False),
    sa.Column('poder_key', sa.String(length=500), nullable=True),
    sa.Column('comprobante_pago_key', sa.String(length=500), nullable=False),
    sa.Column('validado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('propiedades', sa.Column('destacada', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('propiedades', sa.Column('solicitud_documento_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'propiedades', 'solicitudes_documentos_propietario', ['solicitud_documento_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propiedades', type_='foreignkey')
    op.drop_column('propiedades', 'solicitud_documento_id')
    op.drop_column('propiedades', 'destacada')
    op.drop_table('solicitudes_documentos_propietario')
    # ### end Alembic commands ###
