"""solicitudes_sugerencias

Revision ID: e8f3e5751cac
Revises: ea565cb280bb
Create Date: 2026-08-08 17:58:54.072274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8f3e5751cac'
down_revision: Union[str, None] = 'ea565cb280bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sugerencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('medio_comunicacion', sa.String(length=20), nullable=True),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.Column('sugerencia', sa.Text(), nullable=False),
    sa.Column('desea_contacto', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_sugerencias')
    # ### end Alembic commands ###
