"""propiedad video opcional

Revision ID: ea565cb280bb
Revises: e1e2cae50d8d
Create Date: 2026-08-07 21:29:33.746657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea565cb280bb'
down_revision: Union[str, None] = 'e1e2cae50d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('video_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propiedades', 'video_key')
    # ### end Alembic commands ###
